### ISSUE TITLE
Egress rate limiting / English wiki

### ISSUE THREAD

**Issue by fabio-s-franco** [f5devcentral/container-egress-service#26]
The wiki is only partially available in english so it's quite difficult to determine if my use case is covered by f5.

Roughly I am looking for a way to apply egress rate-limiting (not the same as bandwidth) from pods in the cluster towards rate limited external services.

This is to avoid being blocked by these external services, where multiple pods can make calls to them using a single tenant and therefore limited by the same pool.

Example:
ExternalService = 30 calls per minute. More than that calls get blocked for an unknown amount of time, causing unavailability for long periods.

Egress Rate limiting

Pod1 \
Pod2 -=== calls ===> ExternalService
Pod3 /

if calls >= 20 minute, never make the call to ExternalService and return 429.

This is the feature I am looking for.

**Comment by myf5** [comment]
Hi @fabio-s-franco, I think we can do as follow:
Utilize the "bandwidth" in the CRD, but actually the F5 iRule do the limiting. The bandwidth in the yaml actually just let the controller to config F5 to reference an iRule that existing in the F5 BIG-IP. So here we can just input the iRule name, the content of the iRule can be anything. 

```
apiVersion: kubeovn.io/v1alpha1
kind: ExternalService
metadata:
  name: ns600-baidu-bwc
  namespace: ns-600
spec:
  addresses:
  - www.baidu.com
  ports:
  - bandwidth: bwc-2mbps-irule <<<<<<<<<<<<<here, just refer an iRule name
    name: tcp-80
    port: "80"
    protocol: TCP

```
In the F5, the final configurations will be like:
Rule1:   pod1, pod2, pod3 ------> target service : (Attaching an iRule)

The key thing is the iRule need maintain a table/key to store the counter of the request and the time, to make sure  limit the requests on the external svc. Because the irule will be triggered each matching, for example:
Pod 1 calls it, match the rule, will trigger the rule, and it calls 15 requests.
At the same time, Pod 2 calls, match the rule as well, and trigger the rule, calls 5 requests.
We need use iRule table command to count 15+5 and store it and maintain it.
Here are some reference about table and example:
https://www.resdevops.com/2014/04/01/api-rate-shaping-with-f5-irules/
https://community.f5.com/t5/technical-articles/advanced-irules-tables/ta-p/290369


All content in the wiki include English version, just click all wiki that start with EN_** at the right list.
