### ISSUE TITLE
in release 0.5.1, with default configmap templete of ces, the port number of log pool server will be set to "0".

### ISSUE THREAD

**Issue by yxq-yxq** [f5devcentral/container-egress-service#6]
ces release: 0.5.1
in ces configmap templete, the log pool server address entry does not contain port setting, for example:
```
    logPool:
      loggingEnabled: true
      enableRemoteLog: true
      serverAddresses:
        - "10.0.30.106"
```
in this case, the port number of log pool server in bigip will be set to "0". 

It is recommended to add the log pool server's port settings in ces configmap so that the user can define it according to their own environment.
