### ISSUE TITLE
Modifying the ExternalService configuration will affect the corresponding ServiceEgressRule setting

### ISSUE THREAD

**Issue by yxq-yxq** [f5devcentral/container-egress-service#8]
I have a ExternalService and a corresponding ServiceEgressRule, like this:

```
CES release: 0.5.3:
ExternalService:
kind: ExternalService
apiVersion: kubeovn.io/v1alpha1
metadata:
   name: es-test
   namespace: default
spec:
  addresses:
    - 10.1.1.1
  ports:
    - name: tcp-443
      protocol: TCP
      port: "443"

ServiceEgressRule:
apiVersion: kubeovn.io/v1alpha1
kind: ServiceEgressRule
metadata:
  name: ser-test
  namespace: default
spec:
  service: nginx-service-root
  action: accept-decisively
  logging: true
  externalServices:
    - es-test
  logging: true
```

After modifying the ServiceEgressRule configuration and applying the change, for example change the "address“ from "10.1.1.1" to "10.1.1.2 and 10.1.1.2", the "source" setting of the corresponding ServiceEgressRule in AFM will be changed to "Any", like this:

before:
![image](https://user-images.githubusercontent.com/96804048/148174904-16652cac-31c3-4cca-914b-dd9c09d7ee30.png)

after:
![image](https://user-images.githubusercontent.com/96804048/148174934-050cd68b-8630-44b6-bcb3-4c8326feb2bd.png)

Thanks.
